export const iconNames = {
  home: "https://www.svgrepo.com/show/529026/home.svg",
  clock: "https://www.svgrepo.com/show/532104/clock-five.svg",
  photo: "https://www.svgrepo.com/show/522624/photo.svg",
  radar: "https://www.svgrepo.com/show/523644/radar-2.svg",
  stelletite: "https://www.svgrepo.com/show/470683/satellite.svg",
  lightning: "https://www.svgrepo.com/show/479288/lightning.svg",
  snow: "https://www.svgrepo.com/show/532062/snow-alt.svg",
  temperature: "https://www.svgrepo.com/show/266528/temperature.svg",
  siren: "https://www.svgrepo.com/show/279514/siren-siren.svg",
  warning: "https://www.svgrepo.com/show/502912/warning-1.svg",
  share: "https://www.svgrepo.com/show/524953/share.svg",
  microphone: "https://www.svgrepo.com/show/524743/microphone-3.svg",
  tabs: "https://www.svgrepo.com/show/310074/tabs.svg",
};
export const dailyData = [
  {
    date: "15 Temmuz",
    day: "Pazartesi",
    minT: 24,
    maxT: 34,
    iconName: "pb",
    stateCode: "PB",
    windState: "Kuzeydoğudan 8 m/s",
    humidity: "%32 - %82",
  },
  {
    date: "16 Temmuz",
    day: "Salı",
    minT: 25,
    maxT: 34,
    iconName: "pb",
    stateCode: "PB",
    windState: "Kuzeydoğudan 8 m/s",
    humidity: "%36 - %91",
  },
  {
    date: "17 Temmuz",
    day: "Çarşamba",
    minT: 25,
    maxT: 35,
    iconName: "sck",
    stateCode: "SCK",
    windState: "Kuzeydoğudan 8 m/s",
    humidity: "%40 - %93",
  },
  {
    date: "18 Temmuz",
    day: "Perşembe",
    minT: 26,
    maxT: 36,
    iconName: "sck",
    stateCode: "SCK",
    windState: "Kuzeydoğudan 7 m/s",
    humidity: "%38 - %90",
  },
  {
    date: "19 Temmuz",
    day: "Cuma",
    minT: 26,
    maxT: 32,
    iconName: "sck",
    stateCode: "SCK",
    windState: "Kuzeydoğudan 9 m/s",
    humidity: "%58 - %68",
  },
];
export const hourlyData = [
  {
    hour: "18:00",
    iconName: "ab",
    stateCode: "AB",
    temperature: 31,
    feelTemperature: 32,
    humidity: 45,
    windDirection: "K",
    windVelocity: "8",
  },
  {
    hour: "21:00",
    iconName: "ab",
    stateCode: "AB",
    temperature: 27,
    feelTemperature: 30,
    humidity: 77,
    windDirection: "KD",
    windVelocity: "6",
  },
  {
    hour: "00:00",
    iconName: "ab",
    stateCode: "AB",
    temperature: 26,
    feelTemperature: 26,
    humidity: 86,
    windDirection: "K",
    windVelocity: "4",
  },
  {
    hour: "03:00",
    iconName: "pb",
    stateCode: "PB",
    temperature: 25,
    feelTemperature: 25,
    humidity: 91,
    windDirection: "K",
    windVelocity: "4",
  },
  {
    hour: "06:00",
    iconName: "pb",
    stateCode: "PB",
    temperature: 25,
    feelTemperature: 25,
    humidity: 89,
    windDirection: "KD",
    windVelocity: "3",
  },
  {
    hour: "09:00",
    iconName: "pb",
    stateCode: "PB",
    temperature: 27,
    feelTemperature: 29,
    humidity: 65,
    windDirection: "KD",
    windVelocity: "3",
  },
  {
    hour: "12:00",
    iconName: "pb",
    stateCode: "PB",
    temperature: 31,
    feelTemperature: 33,
    humidity: 47,
    windDirection: "KD",
    windVelocity: "5",
  },
  {
    hour: "15:00",
    iconName: "pb",
    stateCode: "PB",
    temperature: 34,
    feelTemperature: 34,
    humidity: 37,
    windDirection: "KD",
    windVelocity: "8",
  },
  {
    hour: "18:00",
    iconName: "pb",
    stateCode: "PB",
    temperature: 31,
    feelTemperature: 32,
    humidity: 45,
    windDirection: "KD",
    windVelocity: "8",
  },
  {
    hour: "21:00",
    iconName: "pb",
    stateCode: "PB",
    temperature: 27,
    feelTemperature: 30,
    humidity: 78,
    windDirection: "KD",
    windVelocity: "6",
  },
  {
    hour: "00:00",
    iconName: "pb",
    stateCode: "PB",
    temperature: 26,
    feelTemperature: 26,
    humidity: 91,
    windDirection: "KD",
    windVelocity: "4",
  },
];
